:: Generated by Sussy Compiler ::
nasm -f win32 -gcv8 bin\main.sus.asm
link /subsystem:console /nodefaultlib /entry:main /debug /pdb:sus.pdb "bin\main.sus.obj" "C:\Program Files (x86)\Windows Kits\10\Lib\10.0.22621.0\um\x86\kernel32.lib" "C:\Program Files (x86)\Windows Kits\10\Lib\10.0.22621.0\ucrt\x86\ucrt.lib"